### ISSUE TITLE
Code license

### ISSUE THREAD

**Issue by viciious** [Kalmalyzer/adpcm-68k#2]
Hi!

Just wanted to ask you which license the 680x0 code is distributed under. 

Thanks for your work!

**Comment by Kalmalyzer** [comment]
Hi! Thanks for asking -- it is now published under the [MIT license](https://github.com/Kalmalyzer/adpcm-68k/commit/46326b4ab64eebf7ca27ae6105a9941389b14c1b).

**Comment by viciious** [comment]
Thanks for the clarification and your choice of license as well! :)
